on:
 push:
 branches:
    -master




  jobs:
    build:
     runs-on:ubuntu-latest

    steps:
   - name: 'testing git hub action'
   action: pwd

   - name: 'testing branch'
  action : echo mahmoud
